spring.application.name=LibraryDemo
server.port=8080

library.name-of-the-library=The MIW-NN Library of useless facts

logging.level.org.springframework=WARN
logging.level.nl.miwnn.ch19.vincent.LibraryDemo=INFO

spring.jpa.hibernate.ddl-auto=none